apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news-db-deployment
spec:
  selector:
    matchLabels:
      app: postegresdb
  template:
    metadata:
      labels: 
        app: postegresdb
    spec:
      containers:
        - name: postegres
          image: postgres:14.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kubedevnews
            - name: POSTGRES_USER
              value: kubedevnews
            - name: POSTGRES_PASSWORD
              value: Pg#123

---

apiVersion: v1
kind: Service
metadata:
  name: kube-news-service
spec:
  selector:
    app: postegresdb
  ports:
    - port: 5432
      targetPort: 5432

---

